// export CATEGORY enum {
//     ACTION = "action", 
// }

export enum CATEGORY {
    BOOKS= "BOOKS",
    CLOTHING= "CLOTHING",
    ENTERTAINMENT= "ENTERTAINMENT",
    ELETRONICS= "ELETRONICS",
    FURNITURE= "FURNITURE",
    IMOBILIARY= "IMOBILIARY",
    KITCHEN= "KITCHEN",
    SCHOOL_SUPPLIES= "SCHOOL_SUPPLIES",
    VEHICLES= "VEHICLES",
}